name: Release

on:
  workflow_dispatch:
  # push:
  #     tags:
  #       - release/*-base

jobs:
  release:
    runs-on: macos-13
    # runs-on: macos-13-xlarge # M1 CPU runner requires billing setup
    steps:
      - uses: actions/checkout@v3
      - run: ./ci/release_branch.sh
      - name: release-macos
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          ./ci/release.sh "${{runner.workspace}}" 2 $(git branch --show-current)-base
